// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  content_form: dynamic(() => import("./ContactForm")),
  gallery: dynamic(() => import("./Gallery")),
  grid_image4: dynamic(() => import("./GridImage4")),
  hero_fullwidth: dynamic(() => import("./HeroFullwidth")),
  navigation_item: dynamic(() => import("./NavigationItem")),
  text: dynamic(() => import("./Text")),
  video: dynamic(() => import("./Video")),
  hero: dynamic(() => import("./Hero")),
  image: dynamic(() => import("./Image")),
  image_cards: dynamic(() => import("./ImageCards")),
  quote: dynamic(() => import("./Quote")),
  text_with_image: dynamic(() => import("./TextWithImage")),
};
